controllers/posts.py
from db import get_db
from flask import render_template, session, abort, request, flash, url_for, redirect, Blueprint

posts_page = Blueprint('posts_page', __name__, template_folder='templates')


@posts_page.route('/posts')
def get():
    db = get_db()
    cur = db.execute('select * from posts order by id desc')
    posts = cur.fetchall()
    return render_template('posts.html', posts=posts)


@posts_page.route('/posts', methods=['POST'])
def post():
    if not session.get('logged_in'):
        abort(401)
    db = get_db()
    db.execute('insert into posts (title, text) values (?, ?)',
               [request.form['title'], request.form['text']])
    db.commit()
    flash('New entry was successfully posted')
    return redirect(url_for('posts_page.get'))

controllers/users.py
from flask import request, session, flash, redirect, url_for, render_template, Blueprint, current_app

users_page = Blueprint('users_page', __name__, template_folder='templates')


@users_page.route('/login', methods=['GET', 'POST'])
def login():
    error = None
    if request.method == 'POST':
        if request.form['username'] != current_app.config['USERNAME']:
            error = 'Invalid username'
        elif request.form['password'] != current_app.config['PASSWORD']:
            error = 'Invalid password'
        else:
            session['logged_in'] = True
            flash('You were logged in')
            return redirect(url_for('posts_page.get'))
    return render_template('login.html', error=error)


@users_page.route('/logout')
def logout():
    session.pop('logged_in', None)
    flash('You were logged out')
    return redirect(url_for('users_page.login'))

main.py
import os
from flask import Flask, g
from controllers.users import users_page
from controllers.posts import posts_page

config_path = os.path.join(os.path.dirname(__file__), 'config.json')

# создаём наше маленькое приложение :)
app = Flask(__name__)
app.config.from_json(config_path)
app.register_blueprint(users_page)
app.register_blueprint(posts_page)


@app.teardown_appcontext
def close_db(error):
    """Closes the database again at the end of the request."""
    if hasattr(g, 'sqlite_db'):
        g.sqlite_db.close()


if __name__ == '__main__':
    app.run()

templates/layout.html
<!doctype html>
<title>Social-network</title>
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='style.css') }}">
<div class=page>
  <h1>Social-network</h1>
  <div class=metanav>
  {% if not session.logged_in %}
    <a href="{{ url_for('users_page.login') }}">log in</a>
  {% else %}
    <a href="{{ url_for('users_page.logout') }}">log out</a>
  {% endif %}
  </div>
  {% for message in get_flashed_messages() %}
    <div class=flash>{{ message }}</div>
  {% endfor %}
  {% block body %}{% endblock %}
</div>

templates/login.html
{% extends "layout.html" %}
{% block body %}
  <h2>Login</h2>
  {% if error %}<p class=error><strong>Error:</strong> {{ error }}{% endif %}
  <form action="{{ url_for('users_page.login') }}" method=post>
    <dl>
      <dt>Username:
      <dd><input type=text name=username>
      <dt>Password:
      <dd><input type=password name=password>
      <dd><input type=submit value=Login>
    </dl>
  </form>
{% endblock %}

templates/posts.html
{% extends "layout.html" %}
{% block body %}
  {% if session.logged_in %}
    <form action="{{ url_for('posts_page.post') }}" method=post class=add-entry>
      <dl>
        <dt>Title:
        <dd><input type=text size=30 name=title>
        <dt>Text:
        <dd><textarea name=text rows=5 cols=40></textarea>
        <dd><input type=submit value=Share>
      </dl>
    </form>
  {% endif %}
  <ul class=entries>
  {% for post in posts %}
    <li><h2>{{ post.title }}</h2>{{ post.text|safe }}
  {% else %}
    <li><em>Unbelievable.  No entries here so far</em>
  {% endfor %}
  </ul>
{% endblock %}